os = require ("os")
const util = require('util')
console.log("temporary directory"+ os.tmpdir())
console.log("hostname: "+os.hostname())
console.log("Os: "+os.platform()+"release:"+os.release())
console.log("uptime: "+(os.uptime()/3600)+"hours")
console.log("userinfo"+util.inspect(os.userInfo()))
console.log("Memory:"+os.totalmem()/100000000+"Giga Byte")
console.log("Free "+ os.freemem()/100000000+"Giga Byte")
console.log("CPU"+util.inspect(os.cpus()))
console.log("Network"+ util.inspect(os.networkInterfaces()))
console.log("Program End")
